services:
  backend:
    image: nadineelsayed/proshop-backend:latest
    platform: linux/arm64
    ports:
      - "5000:5000"
    env_file: .env
    restart: always
  frontend:
    image: nadineelsayed/proshop-frontend:latest
    platform: linux/arm64
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
